import csv
with open('ingredient.csv', mode='w') as recipes:
    recipe_writer = csv.writer(recipes, delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    recipe_writer.writerow(['id', 'name'])
    recipe_writer.writerow(['1', 'Onion']) 
    recipe_writer.writerow(['2', 'Garlic']) 
    recipe_writer.writerow(['3', 'Carrot']) 
    recipe_writer.writerow(['4', 'Celerly']) 
    recipe_writer.writerow(['5', 'Red Capsicum']) 
    recipe_writer.writerow(['6', 'Olive Oil']) 
    recipe_writer.writerow(['7', 'Chilli Powder']) 
    recipe_writer.writerow(['8', 'Ground Cumin']) 
    recipe_writer.writerow(['9', 'Ground Cinnamon']) 
    recipe_writer.writerow(['10', 'Tinned Chickpeas']) 
    recipe_writer.writerow(['11', 'Tinned Red Kidney Beans']) 
    recipe_writer.writerow(['12', 'Tinned Tomatoes']) 
    recipe_writer.writerow(['13', 'Beef Mince']) 
    recipe_writer.writerow(['14', 'Corriader']) 
    recipe_writer.writerow(['15', 'Basamic Vinegar']) 
    recipe_writer.writerow(['16', 'Kent Pumpkin'])
    recipe_writer.writerow(['17', 'Shallots'])
    recipe_writer.writerow(['18', 'Ginger'])
    recipe_writer.writerow(['19', 'Chives'])
    recipe_writer.writerow(['20', 'Mint'], 'Count', '', '', 'true'])
    recipe_writer.writerow(['2', '18', '75', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['2', '19', '0.33', 'Teaspoon', 'fresh', '', 'true'])
    recipe_writer.writerow(['2', '20', '0.33', 'Teaspoon', 'fresh', '', 'true'])
    recipe_writer.writerow(['2', '6', '2 ', 'Tablespoon', 'extra virgin', '', 'false'])
    recipe_writer.writerow(['2', '21', '1000', 'Volume', 'organic', '', 'false'])
    recipe_writer.writerow(['2', '22', '125', 'Volume', '', 'plus extra to serve', 'false'])
    recipe_writer.writerow(['2', '7', '0.5', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['2', '23', '1', 'Count', '', '', 'true'])
   
    # Lazy garlic chicken with butter noodles
    recipe_writer.writerow(['3', '24', '200', 'Weight', 'dried', '', 'false'])
    recipe_writer.writerow(['3', '6', '2', 'Teaspoon', '', '', 'false'])
    recipe_writer.writerow(['3', '25', '600', 'Weight', '', 'trimmed', 'false'])
    recipe_writer.writerow(['3', '26', '80', 'Weight', '', 'chopped', 'false'])
    recipe_writer.writerow(['3', '2', '4', 'Count', 'cloves', 'finely chopped', 'true'])
    recipe_writer.writerow(['3', '27', '250', 'Weight', 'packet', '', 'false'])
    recipe_writer.writerow(['3', '28', '0.25', 'Teaspoon', 'pinch of dried', 'plus extra to serve', 'true'])
    recipe_writer.writerow(['3', '29', '0.33', 'Cup', 'finely chopped fresh continental', 'leaves', 'true'])
    recipe_writer.writerow(['3', '30', '50', 'Weight', 'finely shredded', 'to serve', ''])


    recipe_writer.writerow(['4', '31', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
    recipe_writer.writerow(['4', '', '', '', '', '', ''])
 )
    recipe_writer.writerow(['21', 'Vegatable Stock'])
    recipe_writer.writerow(['22', 'Cocounut Milk'])
    recipe_writer.writerow(['23', 'Lime'])
    recipe_writer.writerow(['24', 'Spaghetti'])
    recipe_writer.writerow(['25', 'Chicken Thigh Fillets'])
    recipe_writer.writerow(['26', 'Butter'])
    recipe_writer.writerow(['27', 'Zucchini Noodles'])
    recipe_writer.writerow(['28', 'Chilli Flakes'])
    recipe_writer.writerow(['29', 'Parsley'])
    recipe_writer.writerow(['30', 'Parmesan'])
    recipe_writer.writerow(['31', 'Tofu'])
    recipe_writer.writerow(['32', 'Rice Noodle'])
    recipe_writer.writerow(['33', 'Cornflour'])
    recipe_writer.writerow(['34', 'Peanut Oil'])
    recipe_writer.writerow(['35', 'Chinese Broccoli'])
    recipe_writer.writerow(['36', 'Soy Sauce'])
    recipe_writer.writerow(['37', 'Brown Sugar'])
    recipe_writer.writerow(['38', 'Egg'])
    recipe_writer.writerow(['39', 'Steak'])
    recipe_writer.writerow(['40', 'Oyster Sauce'])
    recipe_writer.writerow(['41', 'Baby Corn'])
    recipe_writer.writerow(['42', 'Rice'])
    recipe_writer.writerow(['43', 'Curry Paste'])
    recipe_writer.writerow(['44', 'Broccolini'])
    recipe_writer.writerow(['45', 'Baby Carrots'])
    recipe_writer.writerow(['46', 'Lamb Mince'])
    recipe_writer.writerow(['47', 'Mixed Spice'])
    recipe_writer.writerow(['48', 'Turkish Bread'])
    recipe_writer.writerow(['49', 'Pizza Cheese']) 
    recipe_writer.writerow(['50', 'Cherry Tomatoes']) 
    recipe_writer.writerow(['51', 'Lemon']) 
    recipe_writer.writerow(['52', 'Mixed Salad Leaves']) 
    recipe_writer.writerow(['53', 'Mushrooms']) 
    recipe_writer.writerow(['54', 'Sesame Seeds']) 
    recipe_writer.writerow(['55', 'Lemon Juice']) 
    recipe_writer.writerow(['56', 'Miso Paste']) 
    recipe_writer.writerow(['57', 'Bread Rolls']) 
    recipe_writer.writerow(['58', 'Red Cabbage']) 
    recipe_writer.writerow(['59', 'Sprouts']) 
    recipe_writer.writerow(['60', 'Basil']) 
    recipe_writer.writerow(['61', 'Tomato Paste']) 
    recipe_writer.writerow(['62', 'Tomato Passata']) 
    recipe_writer.writerow(['63', 'Whole Chicken']) 
    recipe_writer.writerow(['64', 'Oregano']) 
    recipe_writer.writerow(['65', 'Paprika']) 
    recipe_writer.writerow(['66', 'Corn']) 
    recipe_writer.writerow(['67', 'Spring Onions']) 
    recipe_writer.writerow(['68', 'Baby Gem Lettuce']) 
    recipe_writer.writerow(['69', 'Avocado']) 
    recipe_writer.writerow(['70', 'Buttermilk'])
    recipe_writer.writerow(['71', 'Greek-style Yoghurt'])
    recipe_writer.writerow(['72', 'Breadcrumbs'])
    recipe_writer.writerow(['73', 'Lentils'])
    recipe_writer.writerow(['74', 'Chicken Stock'])
    recipe_writer.writerow(['75', 'Tomatoes'])
    recipe_writer.writerow(['76', 'Ground Corriander'])
    recipe_writer.writerow(['77', 'Cayenne Pepper'])
    recipe_writer.writerow(['78', 'Salt'])    
    recipe_writer.writerow(['79', 'Pepper'])
    recipe_writer.writerow(['80', 'Soba Noodles'])
    recipe_writer.writerow(['81', 'Teriyaki Marinade'])   
    recipe_writer.writerow(['82', 'Lime Juice'])   
    recipe_writer.writerow(['83', 'Sesame Oil'])   
    recipe_writer.writerow(['84', 'Salmon'])   
    recipe_writer.writerow(['85', 'Radishes'])   
    recipe_writer.writerow(['86', 'Baby Cucumbers'])   
    recipe_writer.writerow(['87', 'Tomato Sauce'])   
    recipe_writer.writerow(['88', 'Rice Wine Vinegar'])   
    recipe_writer.writerow(['89', 'Honey'])
    recipe_writer.writerow(['90', 'Gochukang paste'])
    recipe_writer.writerow(['91', 'Ginger'])        
    recipe_writer.writerow(['92', 'Rice Flour'])
    recipe_writer.writerow(['93', 'Vegetable oil'])
    recipe_writer.writerow(['94', 'Snow Peas'])
    recipe_writer.writerow(['95', 'Kale'])
    recipe_writer.writerow(['96', 'Spinach Mix'])
    recipe_writer.writerow(['97', 'Ground Tumeric'])
    recipe_writer.writerow(['98', 'Red Onion'])
    recipe_writer.writerow(['99', 'Dill'])
    recipe_writer.writerow(['100', 'Tabasco Sauce'])
    recipe_writer.writerow(['101', 'Red Wine vinegar'])
    recipe_writer.writerow(['102', 'Baby Spinach'])
    recipe_writer.writerow(['103', 'Zucchini'])
    recipe_writer.writerow(['104', 'Roma Tomatoes'])
    recipe_writer.writerow(['105', 'Pasta'])
    recipe_writer.writerow(['106', 'Pine Nuts'])
    recipe_writer.writerow(['107', 'Baby Rocket Leaves'])
    recipe_writer.writerow(['108', 'Mixed Vegetables'])
    recipe_writer.writerow(['109', 'Beef Stock'])
    recipe_writer.writerow(['110', 'Sweet Potato']) 
    recipe_writer.writerow(['111', 'Goat Cheese'])
    recipe_writer.writerow(['112', 'Chicken Breast'])
    recipe_writer.writerow(['113', 'Chinese Cabbage'])
    recipe_writer.writerow(['114', 'Apple'])
    recipe_writer.writerow(['115', 'Nori'])
    recipe_writer.writerow(['116', 'Mirin'])
    recipe_writer.writerow(['117', 'Sushi Seasoning'])
    recipe_writer.writerow(['118', 'Plain Flour'])
    recipe_writer.writerow(['119', 'Milk'])
    recipe_writer.writerow(['120', 'Self-raising Flour']) 
    recipe_writer.writerow(['121', 'Butternut Pumpkin'])
#    recipe_writer.writerow(['122', ''])
#    recipe_writer.writerow(['123', ''])
#    recipe_writer.writerow(['124', ''])
#    recipe_writer.writerow(['125', ''])
#    recipe_writer.writerow(['126', ''])
#    recipe_writer.writerow(['127', ''])
#    recipe_writer.writerow(['128', ''])
#    recipe_writer.writerow(['129', ''])
#    recipe_writer.writerow(['130', '']) 
#    recipe_writer.writerow(['131', ''])
#    recipe_writer.writerow(['132', ''])
#    recipe_writer.writerow(['133', ''])
#    recipe_writer.writerow(['134', ''])
#    recipe_writer.writerow(['135', ''])
#    recipe_writer.writerow(['136', ''])
#    recipe_writer.writerow(['137', ''])
#    recipe_writer.writerow(['138', ''])
#    recipe_writer.writerow(['139', ''])
#    recipe_writer.writerow(['140', '']) 
#    recipe_writer.writerow(['141', ''])
#    recipe_writer.writerow(['142', ''])
#    recipe_writer.writerow(['143', ''])
#    recipe_writer.writerow(['144', ''])
#    recipe_writer.writerow(['145', ''])
#    recipe_writer.writerow(['146', ''])
#    recipe_writer.writerow(['147', ''])
#    recipe_writer.writerow(['148', ''])
#    recipe_writer.writerow(['149', ''])
#    recipe_writer.writerow(['150', '']) 
#    recipe_writer.writerow(['151', '']) 
#    recipe_writer.writerow(['152', '']) 
#    recipe_writer.writerow(['153', '']) 
#    recipe_writer.writerow(['154', '']) 
#    recipe_writer.writerow(['155', '']) 
#    recipe_writer.writerow(['156', '']) 
#    recipe_writer.writerow(['157', '']) 
#    recipe_writer.writerow(['158', '']) 
#    recipe_writer.writerow(['159', '']) 
#    recipe_writer.writerow(['160', '']) 
#    recipe_writer.writerow(['161', '']) 
#    recipe_writer.writerow(['162', '']) 
#    recipe_writer.writerow(['163', '']) 
#    recipe_writer.writerow(['164', '']) 
#    recipe_writer.writerow(['165', '']) 
#    recipe_writer.writerow(['166', '']) 
#    recipe_writer.writerow(['167', '']) 
#    recipe_writer.writerow(['168', '']) 
#    recipe_writer.writerow(['169', '']) 
#    recipe_writer.writerow(['170', ''])
#    recipe_writer.writerow(['171', ''])
#    recipe_writer.writerow(['172', ''])
#    recipe_writer.writerow(['173', ''])
#    recipe_writer.writerow(['174', ''])
#    recipe_writer.writerow(['175', ''])
#    recipe_writer.writerow(['176', ''])
#    recipe_writer.writerow(['177', ''])
#    recipe_writer.writerow(['178', ''])    
#    recipe_writer.writerow(['179', ''])
#    recipe_writer.writerow(['180', ''])
#    recipe_writer.writerow(['181', ''])   
#    recipe_writer.writerow(['182', ''])   
#    recipe_writer.writerow(['183', ''])   
#    recipe_writer.writerow(['184', ''])   
#    recipe_writer.writerow(['185', ''])   
#    recipe_writer.writerow(['186', ''])   
#    recipe_writer.writerow(['187', ''])   
#    recipe_writer.writerow(['188', ''])   
#    recipe_writer.writerow(['189', ''])
#    recipe_writer.writerow(['190', ''])
#    recipe_writer.writerow(['191', ''])        
#    recipe_writer.writerow(['192', ''])
#    recipe_writer.writerow(['193', ''])
#    recipe_writer.writerow(['194', ''])
#    recipe_writer.writerow(['195', ''])
#    recipe_writer.writerow(['196', ''])
#    recipe_writer.writerow(['197', ''])
#    recipe_writer.writerow(['198', ''])
#    recipe_writer.writerow(['199', ''])

#   recipe_writer.writerow(['100', ''])
#   recipe_writer.writerow(['101', ''])
#   recipe_writer.writerow(['102', ''])
#   recipe_writer.writerow(['103', ''])
#   recipe_writer.writerow(['104', ''])
#   recipe_writer.writerow(['105', ''])
#   recipe_writer.writerow(['106', ''])
#   recipe_writer.writerow(['107', ''])
#   recipe_writer.writerow(['108', ''])
#   recipe_writer.writerow(['109', ''])
#   recipe_writer.writerow(['110', '']) 
#   recipe_writer.writerow(['111', ''])
#   recipe_writer.writerow(['112', ''])
#   recipe_writer.writerow(['113', ''])
#   recipe_writer.writerow(['114', ''])
#   recipe_writer.writerow(['115', ''])
#   recipe_writer.writerow(['116', ''])
#   recipe_writer.writerow(['117', ''])
#   recipe_writer.writerow(['118', ''])
#   recipe_writer.writerow(['119', ''])
#   recipe_writer.writerow(['120', '']) 
#   recipe_writer.writerow(['121', ''])
#   recipe_writer.writerow(['122', ''])
#   recipe_writer.writerow(['123', ''])
#   recipe_writer.writerow(['124', ''])
#   recipe_writer.writerow(['125', ''])
#   recipe_writer.writerow(['126', ''])
#   recipe_writer.writerow(['127', ''])
#   recipe_writer.writerow(['128', ''])
#   recipe_writer.writerow(['129', ''])
#   recipe_writer.writerow(['130', '']) 
#   recipe_writer.writerow(['131', ''])
#   recipe_writer.writerow(['132', ''])
#   recipe_writer.writerow(['133', ''])
#   recipe_writer.writerow(['134', ''])
#   recipe_writer.writerow(['135', ''])
#   recipe_writer.writerow(['136', ''])
#   recipe_writer.writerow(['137', ''])
#   recipe_writer.writerow(['138', ''])
#   recipe_writer.writerow(['139', ''])
#   recipe_writer.writerow(['140', '']) 
#   recipe_writer.writerow(['141', ''])
#   recipe_writer.writerow(['142', ''])
#   recipe_writer.writerow(['143', ''])
#   recipe_writer.writerow(['144', ''])
#   recipe_writer.writerow(['145', ''])
#   recipe_writer.writerow(['146', ''])
#   recipe_writer.writerow(['147', ''])
#   recipe_writer.writerow(['148', ''])
#   recipe_writer.writerow(['149', ''])
#   recipe_writer.writerow(['150', '']) 
#   recipe_writer.writerow(['151', '']) 
#   recipe_writer.writerow(['152', '']) 
#   recipe_writer.writerow(['153', '']) 
#   recipe_writer.writerow(['154', '']) 
#   recipe_writer.writerow(['155', '']) 
#   recipe_writer.writerow(['156', '']) 
#   recipe_writer.writerow(['157', '']) 
#   recipe_writer.writerow(['158', '']) 
#   recipe_writer.writerow(['159', '']) 
#   recipe_writer.writerow(['160', '']) 
#   recipe_writer.writerow(['161', '']) 
#   recipe_writer.writerow(['162', '']) 
#   recipe_writer.writerow(['163', '']) 
#   recipe_writer.writerow(['164', '']) 
#   recipe_writer.writerow(['165', '']) 
#   recipe_writer.writerow(['166', '']) 
#   recipe_writer.writerow(['167', '']) 
#   recipe_writer.writerow(['168', '']) 
#   recipe_writer.writerow(['169', '']) 
#   recipe_writer.writerow(['170', ''])
#   recipe_writer.writerow(['171', ''])
#   recipe_writer.writerow(['172', ''])
#   recipe_writer.writerow(['173', ''])
#   recipe_writer.writerow(['174', ''])
#   recipe_writer.writerow(['175', ''])
#   recipe_writer.writerow(['176', ''])
#   recipe_writer.writerow(['177', ''])
#   recipe_writer.writerow(['178', ''])    
#   recipe_writer.writerow(['179', ''])
#   recipe_writer.writerow(['180', ''])
#   recipe_writer.writerow(['181', ''])   
#   recipe_writer.writerow(['182', ''])   
#   recipe_writer.writerow(['183', ''])   
#   recipe_writer.writerow(['184', ''])   
#   recipe_writer.writerow(['185', ''])   
#   recipe_writer.writerow(['186', ''])   
#   recipe_writer.writerow(['187', ''])   
#   recipe_writer.writerow(['188', ''])   
#   recipe_writer.writerow(['189', ''])
#   recipe_writer.writerow(['190', ''])
#   recipe_writer.writerow(['191', ''])        
#   recipe_writer.writerow(['192', ''])
#   recipe_writer.writerow(['193', ''])
#   recipe_writer.writerow(['194', ''])
#   recipe_writer.writerow(['195', ''])
#   recipe_writer.writerow(['196', ''])
#   recipe_writer.writerow(['197', ''])
#   recipe_writer.writerow(['198', ''])
#   recipe_writer.writerow(['199', ''])
