import csv
with open('recipeToIngredient.csv', mode='w') as recipes:
    recipe_writer = csv.writer(recipes, delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    recipe_writer.writerow(['recipe', 'ingredient', 'quantity', 'measurement', 'description', 'notes', 'optional'])
    #Chilli con carne
    recipe_writer.writerow(['1', '1', '2', 'Count', 'medium', '', 'true'])
    recipe_writer.writerow(['1', '2', '2', 'Count', '', '', 'true'])
    recipe_writer.writerow(['1', '3', '2', 'Count', 'medium', '', 'true'])
    recipe_writer.writerow(['1', '4', '2', 'Count', 'sticks', '', 'true'])
    recipe_writer.writerow(['1', '5', '2', 'Count', '', '', 'true'])
    recipe_writer.writerow(['1', '6', '2', 'Tablespoon', '', '', 'false'])
    recipe_writer.writerow(['1', '7', '1', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['1', '8', '1', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['1', '9', '1', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['1', '10', '400', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['1', '11', '400', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['1', '12', '800', 'Weight', 'chopped', '', 'false'])
    recipe_writer.writerow(['1', '13', '500', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['1', '14', '15', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['1', '15', '2', 'Tablespoon', '', '', 'true'])
                         
    # Pumpkin and Ginger Soup
    recipe_writer.writerow(['2', '16', '1000', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['2', '17', '2', 'Count', '', '', 'true'])
    recipe_writer.writerow(['2', '18', '75', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['2', '19', '0.33', 'Teaspoon', 'fresh', '', 'true'])
    recipe_writer.writerow(['2', '20', '0.33', 'Teaspoon', 'fresh', '', 'true'])
    recipe_writer.writerow(['2', '6', '2 ', 'Tablespoon', 'extra virgin', '', 'false'])
    recipe_writer.writerow(['2', '21', '1000', 'Volume', 'organic', '', 'false'])
    recipe_writer.writerow(['2', '22', '125', 'Volume', '', 'plus extra to serve', 'false'])
    recipe_writer.writerow(['2', '7', '0.5', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['2', '23', '1', 'Count', '', '', 'true'])
   
    # Lazy garlic chicken with butter noodles
    recipe_writer.writerow(['3', '24', '200', 'Weight', 'dried', '', 'false'])
    recipe_writer.writerow(['3', '6', '2', 'Teaspoon', '', '', 'false'])
    recipe_writer.writerow(['3', '25', '600', 'Weight', '', 'trimmed', 'false'])
    recipe_writer.writerow(['3', '26', '80', 'Weight', '', 'chopped', 'false'])
    recipe_writer.writerow(['3', '2', '4', 'Count', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['3', '27', '250', 'Weight', 'packet', '', 'false'])
    recipe_writer.writerow(['3', '28', '0.25', 'Teaspoon', 'pinch of dried', 'plus extra to serve', 'true'])
    recipe_writer.writerow(['3', '29', '0.33', 'Cup', 'finely chopped fresh continental', 'leaves', 'true'])
    recipe_writer.writerow(['3', '30', '50', 'Weight', 'finely shredded', 'to serve', 'true'])
    
    # Vegan pad see ew
    recipe_writer.writerow(['4', '31', '300', 'Weight', 'firm', '', 'false'])
    recipe_writer.writerow(['4', '32', '450', 'Weight', 'fresh wide', '', 'false'])
    recipe_writer.writerow(['4', '33', '2', 'Count', '', '', 'false'])
    recipe_writer.writerow(['4', '34', '1.33', 'Cup', '', '', 'false'])
    recipe_writer.writerow(['4', '35', '1', 'Count', 'bunch', 'chopped, stems halved', 'true'])
    recipe_writer.writerow(['4', '2', '3', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['4', '36', '4', 'Tablespoon', 'light and dark', '2 of each', 'false'])
    #recipe_writer.writerow(['4', '36', '2', 'Tablespoon', 'light', '', 'false'])
    #recipe_writer.writerow(['4', '36', '2', 'Tablespoon', 'dark', '', 'false'])
    recipe_writer.writerow(['4', '37', '2', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['4', '38', '1', 'Count', '', 'lightly beaten', 'false'])

    # Basic beef and vegetable stir-fry
    recipe_writer.writerow(['5', '34', '1.5', 'Tablespoon', '', '', 'false'])
    recipe_writer.writerow(['5', '39', '500', 'Weight', 'lean beef rump', 'cut accross the grain into thin strips', 'false'])
    recipe_writer.writerow(['5', '1', '1', 'Count', '', 'halved, thinly sliced', 'true'])
    recipe_writer.writerow(['5', '5', '1', 'Count', 'large', 'cut into short, thin strips', 'true'])
    recipe_writer.writerow(['5', '40', '125', 'Weight', 'packet', 'halved lengthways', 'true'])
    recipe_writer.writerow(['5', '41', '1', 'Count', 'bunch', 'cut into 4cm lengths', 'true'])
    recipe_writer.writerow(['5', '122', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['5', '42', '2', 'Tablespoon', '', '', 'false'])
    recipe_writer.writerow(['5', '36', '1.5', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['5', '2', '2', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['5', '43', '1', 'Count', 'medium-grain white', 'steamed, to serve', 'true'])
    # Vegetarian Thai curry tray bake
    recipe_writer.writerow(['6', '44', '3', 'Tablespoon', 'yellow', '', 'false'])
    recipe_writer.writerow(['6', '22', '400', 'Volume', 'can', '', 'false'])
    recipe_writer.writerow(['6', '41', '1', 'Count', 'bunch', 'trimmed, halved lengthways', 'true'])
    recipe_writer.writerow(['6', '40', '125', 'Weight', 'packet', '', 'true'])
    recipe_writer.writerow(['6', '16', '750', 'Weight', 'deseeded, cut into 1cm-thick wedges', '', 'true'])
    recipe_writer.writerow(['6', '45', '6', 'Count', '', 'trimmed', 'true'])
    recipe_writer.writerow(['6', '31', '300', 'Weight', 'firm', 'cut into 2cm pieces', 'true'])
    recipe_writer.writerow(['6', '43', '250', 'Weight', 'brown', '', 'true'])
    recipe_writer.writerow(['6', '14', '15', 'Weight', 'fresh', 'to serve', 'true'])
    recipe_writer.writerow(['6', '23', '1', 'Count', '', 'halves, to serve', 'true'])

    # Quick Turkish lamb pizzas
    recipe_writer.writerow(['7', '6', '3', 'Teaspoon', '', '', 'false'])
    recipe_writer.writerow(['7', '46', '500', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['7', '1', '1', 'Count', 'small', 'finely chopped', 'true'])
    recipe_writer.writerow(['7', '2', '2', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['7', '47', '1', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['7', '48', '400', 'Weight', '', 'split horizontally', 'true'])
    recipe_writer.writerow(['7', '38', '4', 'Count', '', 'lightly whisked', 'true'])
    recipe_writer.writerow(['7', '49', '120', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['7', '29', '0.25', 'Cup', 'flat-leaf', '', 'true'])
    recipe_writer.writerow(['7', '50', '100', 'Weight', '', 'halved', 'true'])
    recipe_writer.writerow(['7', '6', '2', 'Tablespoon', '', 'extra, to serve', 'true'])
    recipe_writer.writerow(['7', '51', '1', 'Count', '', 'wedges, to serve', 'true'])
    recipe_writer.writerow(['7', '52', '1', 'Count', '', 'to serve', 'true'])

    # Asian-style mushroom burger 
    recipe_writer.writerow(['8', '53', '4', 'Count', 'large field', '', 'false'])
    recipe_writer.writerow(['8', '36', '2', 'Tablespoon', 'sweet', '', 'true'])
    recipe_writer.writerow(['8', '54', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['8', '69', '1', 'Count', '', 'stoned, peeled, mashed', 'true'])
    recipe_writer.writerow(['8', '55', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['8', '56', '1', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['8', '57', '4', 'Count', 'Harvest Grain', 'split, toasted', 'false'])
    recipe_writer.writerow(['8', '58', '80', 'Weight', '', 'finely shredded', 'true'])
    recipe_writer.writerow(['8', '3', '1', 'Count', '', 'peeled, finely shredded', 'true'])
    recipe_writer.writerow(['8', '59', '20', 'Weight', 'alfafa', '', 'true'])

    # Gluten-free Italian meatballs and spaghetti
    recipe_writer.writerow(['9', '123', '500', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['9', '2', '2', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['9', '29', '2', 'Tablespoon', '', 'chopped', 'true'])
    recipe_writer.writerow(['9', '60', '1', 'Tablespoon', '', 'chopped', 'true'])
    recipe_writer.writerow(['9', '30', '25', 'Weight', '', 'finely grated', 'true'])
    recipe_writer.writerow(['9', '61', '140', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['9', '6', '1', 'Tablespoon', '', '', 'false'])
    recipe_writer.writerow(['9', '1', '1', 'Count', 'small', 'finely chopped', 'true'])
    recipe_writer.writerow(['9', '62', '700', 'Volume', '', '', 'false'])
    recipe_writer.writerow(['9', '24', '500', 'Weight', 'gluten free', '', 'false'])
   
    #  Lemon chicken with smoky corn salad
    recipe_writer.writerow(['10', '63', '1800', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['10', '51', '1', 'Count', '', 'rind finely grated, juiced', 'false'])
    recipe_writer.writerow(['10', '64', '1', 'Tablespoon', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['10', '2', '2', 'Count', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['10', '65', '1.5', 'Teaspoon', 'smoked', '', 'true'])
    recipe_writer.writerow(['10', '6', '100', 'Volume', 'extra virgin', '', 'true'])
    recipe_writer.writerow(['10', '66', '3', 'Count', '', 'cobs, husks and silk removed', 'true'])
    recipe_writer.writerow(['10', '67', '3', 'Count', '', 'ends trimmed', 'true'])
    recipe_writer.writerow(['10', '68', '2', 'Count', '', 'trimmed, cut into wedges', 'true'])
    recipe_writer.writerow(['10', '29', '0.5', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['10', '20', '0.5', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['10', '69', '1', 'Count', '', 'stoned, peeled, sliced', 'true'])
    recipe_writer.writerow(['10', '70', '125', 'Volume', '', '', 'true'])
    recipe_writer.writerow(['10', '71', '2', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['10', '6', '2', 'Tablespoon', 'extra-virgin', '', 'true'])
    recipe_writer.writerow(['10', '29', '1', 'Tablespoon', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['10', '19', '1', 'Tablespoon', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['10', '51', '0.5', 'Count', '', 'rind finely grated, juiced', 'true'])

    # Middle Eastern lamb koftas with aromatic lentil rice
    recipe_writer.writerow(['11', '46', '500', '', '', '', 'false'])
    recipe_writer.writerow(['11', '1', '1', 'Count', '', 'grated', 'true'])
    recipe_writer.writerow(['11', '72', '0.25', 'Cup', 'panko', '', 'true'])
    recipe_writer.writerow(['11', '9', '0.5', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '2', '2', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['11', '14', '2', 'Count', '', '', 'true'])
    recipe_writer.writerow(['11', '73', '420', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['11', '43', '1', 'Cup', 'Basmati', '', 'true'])
    recipe_writer.writerow(['11', '74', '1.5', 'Cup', '', 'liquid', 'true'])
    recipe_writer.writerow(['11', '6', '2', 'Tablespoon', 'extra virgin', '', 'true'])
    recipe_writer.writerow(['11', '71', '0.5', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['11', '75', '3', 'Count', '', '', 'true'])
    recipe_writer.writerow(['11', '8', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '76', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '65', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '77', '0.5', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '78', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['11', '79', '0.5', 'Teaspoon', 'Ground Black', '', 'true'])

    # Salmon and soba noodle bowl
    recipe_writer.writerow(['12', '80', '270', 'Weight', 'packet', '', 'false'])
    recipe_writer.writerow(['12', '81', '125', 'Volume', '', '', 'true'])
    recipe_writer.writerow(['12', '82', '60', 'Volume', '', '', 'true'])
    recipe_writer.writerow(['12', '83', '3', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['12', '67', '2', 'Count', '', 'thinly sliced', 'true'])
    recipe_writer.writerow(['12', '54', '2', 'Tablespoon', '', 'toasted', 'true'])
    recipe_writer.writerow(['12', '84', '4', 'Count', 'skinless', 'portions', 'false'])
    recipe_writer.writerow(['12', '85', '4', 'Count', '', 'thinly sliced', 'true'])
    recipe_writer.writerow(['12', '86', '4', 'Count', '', 'peeled into ribbons', 'true'])
    recipe_writer.writerow(['12', '69', '1', 'Count', 'ripe', 'stoned, peeled, thinly sliced', 'true'])
    recipe_writer.writerow(['12', '3', '1', 'Count', 'large', 'peeled, cut, into long matchsticks', 'true'])
    recipe_writer.writerow(['12', '58', '120', 'Weight', '', 'finely shredded', 'true'])

    # Crispy Korean fried tofu with snow peas
    recipe_writer.writerow(['13', '31', '500', 'Weight', 'firm', '', 'true'])
    recipe_writer.writerow(['13', '87', '0.66', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['13', '36', '0.33', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['13', '88', '0.33', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['13', '89', '2', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['13', '90', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['13', '18', '1', 'Count', 'fresh small', 'peeled, finely grated', 'true'])
    recipe_writer.writerow(['13', '2', '2', 'Count', '', 'crushed', 'true'])
    recipe_writer.writerow(['13', '92', '0.5', 'Cup', '', '', 'true'])
    recipe_writer.writerow(['13', '93', '1', 'Count', '', 'for deep-frying', 'true'])
    recipe_writer.writerow(['13', '94', '150', 'Weight', '', 'trimmed, halved diagonally', 'true'])
    recipe_writer.writerow(['13', '40', '400', 'Weight', 'spears', 'drained, rinsed', 'true'])
    recipe_writer.writerow(['13', '91', '1', 'Tablespoon', 'fresh', 'chopped', 'true'])
    recipe_writer.writerow(['13', '43', '1', 'Count', 'steamed jasmine', 'to serve', 'true'])
    recipe_writer.writerow(['13', '54', '1', 'Count', 'toasted', 'to serve', 'true'])
    recipe_writer.writerow(['13', '14', '1', 'Count', 'fresh', 'to serve', 'true'])

    # 17-minute turmeric chilli fried egg bowl
    recipe_writer.writerow(['14', '6', '2.5', 'Tablespoon', 'extra virgin', '', 'true'])
    recipe_writer.writerow(['14', '2', '3', 'Count', '', 'thinly sliced', 'true'])
    recipe_writer.writerow(['14', '95', '150', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['14', '96', '150', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['14', '10', '425', 'Weight', '', 'rinsed, drained', 'true'])
    recipe_writer.writerow(['14', '51', '1', 'Count', '', 'rind finely grated, juiced', 'true'])
    recipe_writer.writerow(['14', '97', '0.5', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['14', '28', '0.25', 'Teaspoon', 'dried', '', 'true'])
    recipe_writer.writerow(['14', '38', '4', 'Count', '', '', 'true'])
    recipe_writer.writerow(['14', '50', '200', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['14', '98', '0.5', 'Count', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['14', '99', '0.5', 'Cup', '', 'finely chopped', 'true'])
    recipe_writer.writerow(['14', '71', '1', 'Count', '', 'to serve', 'true'])

    # Mexican-style omelette wrap 
    recipe_writer.writerow(['15', '100', '2', 'Teaspoon', 'chipotle', '', 'true'])
    recipe_writer.writerow(['15', '23', '2', 'Count', '', '', 'true'])
    recipe_writer.writerow(['15', '67', '4', 'Count', '', '', 'true'])
    recipe_writer.writerow(['15', '14', '1', 'Count', 'bunch of fresh', '', 'true'])
    recipe_writer.writerow(['15', '101', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['15', '75', '5', 'Count', 'mixed-colour', '', 'true'])
    recipe_writer.writerow(['15', '102', '50', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['15', '38', '6', 'Count', '', '', 'false'])
    recipe_writer.writerow(['15', '6', '2', 'Tablespoon', '', '', 'false'])
    recipe_writer.writerow(['15', '30', '20', 'Weight', '', '', 'true'])
    
    # Vegan pasta salad with green goddess dressing 
    recipe_writer.writerow(['16', '121', '650', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['16', '103', '260', 'Weight', '', 'cut into 2cm pieces', 'true'])
    recipe_writer.writerow(['16', '104', '250', 'Weight', '', 'halved', 'false'])
    recipe_writer.writerow(['16', '105', '250', 'Weight', 'dried fusilli', '', 'false'])
    recipe_writer.writerow(['16', '98', '1', 'Count', 'small', 'thinly sliced', 'true'])
    recipe_writer.writerow(['16', '106', '2', 'Tablespoon', '', 'toasted', 'true'])
    recipe_writer.writerow(['16', '107', '1', 'Count', '', 'to serve', 'true'])
    recipe_writer.writerow(['16', '69', '1', 'Count', 'ripe', 'chopped', 'true'])
    recipe_writer.writerow(['16', '29', '1', 'Count', 'bunch of fresh', 'leaves picked', 'true'])
    recipe_writer.writerow(['16', '2', '2', 'Count', '', 'chopped', 'true'])
    recipe_writer.writerow(['16', '51', '60', 'Volume', 'fresh', '', 'true'])
    recipe_writer.writerow(['16', '6', '2', 'Tablespoon', 'extra virgin', '', 'true'])

    # Speedy shepherd's pie
    recipe_writer.writerow(['17', '108', '400', 'Weight', 'packet', '', 'true'])
    recipe_writer.writerow(['17', '46', '500', 'Weight', '', '', 'false'])
    recipe_writer.writerow(['17', '109', '500', 'Volume', '', 'liquid', 'false'])
    recipe_writer.writerow(['17', '110', '700', 'Weight', '', 'peeled, chopped', 'false'])
    recipe_writer.writerow(['17', '111', '120', 'Weight', 'soft', '', 'true'])

    # Japanese-style shredded chicken salad
    recipe_writer.writerow(['18', '112', '400', 'Weight', 'smoked', 'skin removed, shredded', 'false'])
    recipe_writer.writerow(['18', '113', '160', 'Weight', '', 'shredded', 'true'])
    recipe_writer.writerow(['18', '103', '1', 'Count', 'bunch', 'trimmed, thinly sliced', 'true'])
    recipe_writer.writerow(['18', '114', '2', 'Count', 'small', 'thinly sliced', 'true'])
    recipe_writer.writerow(['18', '58', '0.25', 'Count', 'small', 'shredded', 'true'])
    recipe_writer.writerow(['18', '115', '2', 'Count', 'sheets', 'torn', 'true'])
    recipe_writer.writerow(['18', '56', '3', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['18', '116', '1.5', 'Tablespoon', 'salt-reduced', '', 'true'])
    recipe_writer.writerow(['18', '36', '1.5', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['18', '83', '2', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['18', '54', '1', 'Count', 'white and black', 'to serve', 'true'])

    # Karaage chicken (Fried chicken)
    recipe_writer.writerow(['19', '36', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['19', '117', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['19', '18', '1', 'Tablespoon', '', '', 'true'])
    recipe_writer.writerow(['19', '25', '500', 'Weight', '', 'cut into 3cm pieces', 'true'])
    recipe_writer.writerow(['19', '93', '1', 'Count', '', 'to deep-fry', 'true'])
    recipe_writer.writerow(['19', '33', '130', 'Weight', '', '', 'true'])
    recipe_writer.writerow(['19', '118', '2', 'Tablespoon', '', '', 'true'])

    # Simple crepe recipe
    recipe_writer.writerow(['20', '118', '1', 'Cup', '', '', 'false'])
    recipe_writer.writerow(['20', '78', '.125', 'Teaspoon', '', '', 'true'])
    recipe_writer.writerow(['20', '38', '1', 'Count', '', '', 'false'])
    recipe_writer.writerow(['20', '119', '1', 'Cup', '', '', 'false'])


    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])

    # recipe_writer.writerow(['3', '', '', '', '', '', ''])
    # recipe_writer.writerow(['3', '', '', '', '', '', ''])


