import csv
with open('recipe.csv', mode='w') as recipe:
    recipe_writer = csv.writer(recipe, delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    recipe_writer.writerow(['id', 'name', 'time', 'difficulty', 'notes', 'description', 'cuisine_tags', 'dietary_tags', 'imageRef', 'url', 'method'])

    recipe_writer.writerow(['1', 'Good old chilli con carne', '75', 'Easy', '', "This hearty, all-time classic chilli con carne recipe is hard to beat – delicious!", "Minced beef, Healthy", '0100', '/images/recipe_images/1_chilli_con_carne.jpg', 'https://www.jamieoliver.com/recipes/beef-recipes/good-old-chilli-con-carne/', "Peel and finely chop the onions, garlic, carrots and celery – don’t worry about the technique, just chop away until fine. Halve the red peppers, remove the stalks and seeds and roughly chop. Heat 2 tablespoons of oil in a large casserole pan on a medium-high heat, add the chopped veg, chilli powder, cumin, cinnamon and a good pinch of sea salt and black pepper, then cook for 7 minutes, or until softened, stirring regularly.| Drain and add the chickpeas and kidney beans, tip in the tomatoes, breaking them up with the back of a spoon, then pour in 1 tin's worth of water. Add the minced beef, breaking any larger chunks.| Pick the coriander leaves and put aside, then finely chop and add the stalks to the pan, with the balsamic vinegar. Season with a good pinch of sea salt and black pepper.| Bring to the boil, then reduce the heat to low and simmer with a lid slightly ajar for 1 hour, or until slightly thickened and reduced, stirring occasionally.| Serve up with fluffy rice or couscous, a hunk of crusty bread, or over a jacket potato, with some yoghurt, guacamole, and wedges of lime on the side for squeezing over. Sprinkle over the reserved coriander, and some fresh chilli, if you like, then tuck in."])

    recipe_writer.writerow(['2', 'Pumpkin & ginger soup', '60', 'Intermediate', '', '', "Vegetables, Mains, Light meals", '1111', '/images/recipe_images/2_pumpkin__carne.jpg', 'https://www.jamieoliver.com/recipes/vegetables-recipes/pumpkin-ginger-soup/', "Deseed and roughly chop the pumpkin, peel and chop the shallots, then peel and finely grate the ginger. Pick and finely chop the herbs.| Place the pumpkin, shallots, ginger and some oil in a large saucepan and sauté until soft.| Add the stock, coconut milk and chilli powder. Season, then bring to the boil and simmer for 40 minutes.| Blitz in a food processor then serve with the fresh herbs, lime juice and a splash of coconut milk."])
    
    recipe_writer.writerow(['3', 'Lazy garlic chicken with butter noodles', '30', 'Easy', '', "Ready in 30 minutes, this quick and easy chicken and spaghetti dinner is perfect for those busy school nights.", 'Pasta', '0000', '/images/recipe_images/3_lazy_garlic_chicken_with_butter_noodles.jpg', 'https://www.taste.com.au/recipes/lazy-garlic-chicken-butter-noodles-recipe/', "Cook the spaghetti in a large saucepan of boiling water following packet directions or until al dente. Drain the pasta, reserving 60ml (1/4 cup) of the pasta water.| Meanwhile, heat the oil in a large non-stick frying pan over high heat. Season the chicken and cook for 6 minutes each side or until cooked through. Transfer to a plate to cool slightly before coarsely chopping.| Reduce heat to low. Add the butter and garlic to the frying pan and cook until the butter is foaming and garlic is aromatic. Add the zucchini noodles and chilli, if using.| Return the pasta to the pan with the chicken, zucchini mixture, parsley and enough of the pasta water to create a sauce to coat the pasta and zucchini. Season well then use tongs to toss to combine. Divide pasta mixture among serving bowls and drizzle over the sauce from the pan. Sprinkle with extra parsley. Serve topped with extra chilli and parmesan, if using."])


    recipe_writer.writerow(['4', 'Vegetarian pad see ew', '20', 'Intermediate', '', "Learn how to make a vegetarian version of the traditional Thai pad see ew recipe.", '', '0001', '/images/recipe_images/4_vegetarian_pad_see_ew', 'https://www.taste.com.au/recipes/vegetarian-pad-see-ew/a04ffc0e-04e3-4b70-b5ab-4c32a805fd0b?r=recipes/', "Place tofu on a plate lined with paper towel. Stand for 10 minutes. Pat dry. Cut into 16 cubes.| Place noodles in a heatproof bowl. Cover with boiling water. Set aside for 4 minutes. Using a fork, separate noodles. Drain.| Place cornflour in a large shallow dish. Season with salt and pepper. Heat oil in a wok over high heat. Toss tofu in cornflour until coated. Shake off excess. Shallow-fry tofu for 3 to 4 minutes or until golden and crisp. Remove with slotted spoon. Drain on paper towel. Discard oil.| Heat wok over high heat. Add gai lan stems. Stir-fry for 2 minutes or until tender. Add leaves. Stir-fry for 1 minute or until wilted. Return tofu to wok with noodles, garlic, sauces and sugar. Stir-fry until hot. Make a well in centre of noodles. Add egg. Cook for 2 minutes or until egg starts to set. Stir-fry egg through noodles. Serve."])
        

    recipe_writer.writerow(['5', 'Basic beef and vegetable stir-fry', '20', 'Intermediate', '', "Have dinner on the table in no time with this tasty beef and vegetable stir fry.", 'Tofu, Noodle', '0000', '/images/recipe_images/5_basic_beef_and_vegetable_stiry-fry.jpg', 'https://www.taste.com.au/recipes/basic-beef-vegetable-stir-fry/fc0381ab-8c80-4f39-aaee-1690b09ef221?r=recipes/', "Heat a large wok over high heat. Once the wok is hot, add 1 tablespoon of the oil and carefully swirl around to coat the side of the wok. Heat until very hot.| It is important to heat the wok before adding the oil, otherwise the oil can end up overheating and burning. You will know if the oil is hot enough if the beef starts to sizzle when added to the wok.| Add one-third of the beef strips and stir-fry for 1-2 minutes or until the beef is browned and just cooked. Transfer to a plate. Repeat with the beef in two more batches, reheating the wok between each batch. Remove all beef from the wok.| Adding and cooking the beef in batches is very important as it seals the meat, keeping in the juices. If you add too much meat at once, the wok will lose its heat and the meat will stew and become tough.| Heat remaining oil in the wok over medium-high heat. Add the onion, capsicum, corn and broccolini. Stir-fry for 2 minutes. Add the water, cover and cook for 30-60 seconds or until the vegetables are just tender.| Add the soy sauce, garlic and oyster sauce to the wok. Toss well to combine. Add the beef and toss until heated through. Serve immediately with rice."])



     recipe_writer.writerow(['6', 'Vegetarian Thai curry tray bake', '65', 'Easy', '', "Add a Thai curry twist to this hearty vegetarian tray bake, which is loaded with tofu, pumpkin, carrot and rice.", 'Tofu, Vegetarian Curry', '0001', '/images/recipe_images/6_thai_vego_curry_tray_bake.jpg', 'https://www.taste.com.au/recipes/thai-vego-curry-tray-bake/0c1u0gg4?r=recipes/', "Preheat the oven to 200C/180C fan forced. Heat a large flameproof baking dish over high heat. Add the curry paste and cook, stirring, for 2 minutes or until aromatic. Add half of the coconut milk. Cook, stirring, for 1 minute or until well combined. Add the broccolini, corn and pour over 375ml (1 1/2 cups) water. Top with the pumpkin, carrots and tofu. Bake for 35 minutes or until the pumpkin is tender and the tofu is golden.| Pour over the remaining coconut milk and stir to combine. Sprinkle the rice over the vegies and tofu. Cook for a further 10 minutes or until the rice is warmed through. Top with coriander sprigs and serve with lime halves."])

     recipe_writer.writerow(['7', 'Quick Turkish lamb pizzas', '35', 'Intermediate', '', "For a tasty weeknight meal the whole family will enjoy, try these spiced lamb, cheese and tomato pizzas.", 'Lamb, Family Dinner', '0000', '/images/recipe_images/7_quick_turkish_lamb_pizzas.jpeg', 'https://www.taste.com.au/recipes/quick-turkish-lamb-pizzas/Kpvpxs7Y', "Preheat oven to 190C. Line two baking trays with baking paper.| Heat the oil in a medium frying pan over high heat. Add the lamb and cook, stirring with a wooden spoon to break up lumps, for 4 mins or until browned. Add the onion and cook for 3 mins or until softened. Add the garlic and mixed spice and cook for 1 min or until fragrant. Remove from heat.| Place the bread halves, cut-side up, on the prepared trays. Divide the mince mixture evenly among bread. Crack two eggs over each piece of bread, leaving a 10cm gap between eggs. Sprinkle with cheese. Bake for 15 mins or until the cheese melts. Sprinkle with parsley and tomato. Drizzle with extra oil and cut each pizza into slices. Serve with the lemon wedges and salad leaves."])

     
     recipe_writer.writerow(['8', 'Asian-style mushroom burger', '25', 'Easy', '', "This Asian-style mushroom burger has all the flavour you need.", 'Burger, Mushroom', '0001', '/images/recipe_images/8_asian_mushroom_burger.jpg', 'https://www.taste.com.au/recipes/asian-style-mushroom-burger-recipe/z01zrp7v?r=recipes/', "Heat a large chargrill on medium. Lightly spray each mushroom with olive oil spray and lightly brush with soy sauce. Cook on the grill, turning and brushing with soy sauce, for 5 mins or until mushrooms are almost tender. Sprinkle with sesame seeds and cook for a further 1 min or until sesame seeds are toasted.| Meanwhile, combine the avocado, lemon juice and miso paste in a small bowl. Season.| Spread the avocado mixture evenly over the cut sides of the rolls. Divide the roll bases among serving plates. Top with mushroom, cabbage, carrot and alfalfa sprouts. Top with the roll tops and serve immediately."])

     recipe_writer.writerow(['9', 'Gluten-free Italian meatballs and spaghetti', '85', 'Easy', '', "For a good source of fibre and protein try these Italian-style meatballs served with gluten-free spaghetti, shaved parmesan and fresh basil leaves.", 'Mince', '1000', '/images/recipe_images/9_gluten_free_italian_meatballs_spaghetti.jpg', 'https://www.taste.com.au/recipes/gluten-free-italian-meatballs-spaghetti/LaWQvuhr?r=recipes/', "Place the mince, garlic, parsley, basil, parmesan and 1 tablespoon of tomato paste in a medium bowl. Use your hands to mix until well combined. Shape tablespoons of mince mixture into balls. Place on a plate in the fridge for 30 mins to chill.| Heat the oil in a large saucepan over medium heat. Add the meatballs and cook, turning, for 5 mins or until lightly browned. Transfer to a plate. Cook the onion in the pan, stirring, for 5 mins or until soft. Add the passata, remaining tomato paste and 1 cup (250ml) water. Bring to the boil. Reduce heat to low. Simmer for 10 mins. Add the meatballs and cook, covered, for 15 mins or until the sauce thickens and the meatballs are cooked through.| Meanwhile, cook pasta in a saucepan of boiling water until al dente. Drain well.| Divide the spaghetti, meatballs and pasta sauce among serving bowls."])

     recipe_writer.writerow(['10', 'Lemon chicken with smoky corn salad', '105', 'Easy', '', "For light lunches or dinners, look no further than this delicious lemon chicken with smoky corn salad.", '', '0000', '/images/recipe_images/10_lemon_chicken_with_smoky_corn_salad.jpg', 'https://www.taste.com.au/recipes/lemon-chicken-smoky-corn-salad-recipe/kfdtjefm?utm_source=coles&utm_content=seasonalsides', "Place the chicken, breast-side down, on a clean work surface. Use kitchen scissors to cut along each side of the backbone to remove. Turn chicken over. Use the heel of your hand to press down on the breastbone to flatten. Season.| Combine the lemon rind, lemon juice, oregano, garlic, 1 tsp paprika and ¼ cup (60ml) olive oil in a large bowl. Season. Add the chicken and rub all over with the lemon mixture. Cover and set aside for 30 mins to develop the flavours.| Meanwhile, preheat a chargrill on high. Drizzle the corn with 1½ tbs olive oil. Sprinkle with the remaining paprika. Season. Cook the corn on the grill, turning occasionally, for 12 mins or until tender and charred. Set aside to cool slightly. Use a small serrated knife to cut down the side of the cobs to release the kernels. Transfer the kernels to a large bowl.| Drizzle the spring onion with the remaining olive oil. Season. Cook on the grill, turning, for 2 mins or until tender and charred. Set aside to cool slightly. Coarsely chop and add to the corn in the bowl.| Preheat oven to 200°C. Line a large baking tray with baking paper. Place chicken, breast-side up, on the lined tray. Pour over any lemon mixture from the bowl. Roast for 50 mins or until the chicken is cooked through and juices run clear when the thickest part of the thigh is pierced with a skewer. Cover. Set aside for 10 mins to rest.| To make the buttermilk dressing, place buttermilk, yoghurt, oil, parsley, chive, lemon rind and lemon juice in a screw-top jar. Seal. Shake to combine.| Add the lettuce, parsley, mint and avocado to corn mixture. Drizzle with the dressing. Gently toss to combine. Season. Arrange on a large serving platter with the chicken."])

     recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])


     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])
     # recipe_writer.writerow(['', '', '', '', '', "", '', '0000', '/images/recipe_images/', '', ""])



    
#recipe_writer.writerow([
