import csv
with open('recipe.csv', mode='w') as recipe:
    recipe_writer = csv.writer(recipe, delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    recipe_writer.writerow(['id', 'name', 'time', 'difficulty', 'notes', 'description', 'cuisine_tags', 'dietary_tags', 'imageRef', 'url', 'method'])

    recipe_writer.writerow(['1', 'Good old chilli con carne', '75', 'Easy', '', "This hearty, all-time classic chilli con carne recipe is hard to beat – delicious!", "Minced beef, Healthy", '0100', '/images/recipe_images/1_chilli_con_carne.jpg', 'https://www.jamieoliver.com/recipes/beef-recipes/good-old-chilli-con-carne/', "Peel and finely chop the onions, garlic, carrots and celery – don’t worry about the technique, just chop away until fine. Halve the red peppers, remove the stalks and seeds and roughly chop. Heat 2 tablespoons of oil in a large casserole pan on a medium-high heat, add the chopped veg, chilli powder, cumin, cinnamon and a good pinch of sea salt and black pepper, then cook for 7 minutes, or until softened, stirring regularly.| Drain and add the chickpeas and kidney beans, tip in the tomatoes, breaking them up with the back of a spoon, then pour in 1 tin's worth of water. Add the minced beef, breaking any larger chunks.| Pick the coriander leaves and put aside, then finely chop and add the stalks to the pan, with the balsamic vinegar. Season with a good pinch of sea salt and black pepper.| Bring to the boil, then reduce the heat to low and simmer with a lid slightly ajar for 1 hour, or until slightly thickened and reduced, stirring occasionally.| Serve up with fluffy rice or couscous, a hunk of crusty bread, or over a jacket potato, with some yoghurt, guacamole, and wedges of lime on the side for squeezing over. Sprinkle over the reserved coriander, and some fresh chilli, if you like, then tuck in."])

    recipe_writer.writerow(['2', 'Pumpkin & ginger soup', '60', 'Intermediate', '', '', "Vegetables, Mains, Light meals", '1111', '/images/recipe_images/2_pumpkin__carne.jpg', 'https://www.jamieoliver.com/recipes/vegetables-recipes/pumpkin-ginger-soup/', "Deseed and roughly chop the pumpkin, peel and chop the shallots, then peel and finely grate the ginger. Pick and finely chop the herbs.| Place the pumpkin, shallots, ginger and some oil in a large saucepan and sauté until soft.| Add the stock, coconut milk and chilli powder. Season, then bring to the boil and simmer for 40 minutes.| Blitz in a food processor then serve with the fresh herbs, lime juice and a splash of coconut milk."])
    
    recipe_writer.writerow(['3', 'Lazy garlic chicken with butter noodles', '30', 'Easy', '', "Ready in 30 minutes, this quick and easy chicken and spaghetti dinner is perfect for those busy school nights.", 'Pasta', '0000', '/images/recipe_images/3_lazy_garlic_chicken_with_butter_noodles.jpg', 'https://www.taste.com.au/recipes/lazy-garlic-chicken-butter-noodles-recipe/3dxtyr12?r=quickeasy&h=Quick%20%20easy', "Cook the spaghetti in a large saucepan of boiling water following packet directions or until al dente. Drain the pasta, reserving 60ml (1/4 cup) of the pasta water.| Meanwhile, heat the oil in a large non-stick frying pan over high heat. Season the chicken and cook for 6 minutes each side or until cooked through. Transfer to a plate to cool slightly before coarsely chopping.| Reduce heat to low. Add the butter and garlic to the frying pan and cook until the butter is foaming and garlic is aromatic. Add the zucchini noodles and chilli, if using.| Return the pasta to the pan with the chicken, zucchini mixture, parsley and enough of the pasta water to create a sauce to coat the pasta and zucchini. Season well then use tongs to toss to combine. Divide pasta mixture among serving bowls and drizzle over the sauce from the pan. Sprinkle with extra parsley. Serve topped with extra chilli and parmesan, if using."])


        
#recipe_writer.writerow([
