import csv
with open('equipment.csv', mode='w') as equipment:
    #print('equipment.csv generated')
    equipment_writer = csv.writer(equipment, delimiter = ',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    equipment_writer.writerow(['id', 'name'])
    #Chilli con carne
    equipment_writer.writerow(['1', 'Large Casserole Pan'])
    equipment_writer.writerow(['2', 'Large Saucepan'])
    equipment_writer.writerow(['3', 'Large Frying Pan'])
    equipment_writer.writerow(['4', 'Wok'])
    equipment_writer.writerow(['5', 'Medium Heatproof Bowl'])
    equipment_writer.writerow(['6', 'Large Shallow Dish'])
    equipment_writer.writerow(['7', 'Large Baking Dish (Flame Proof)'])
    equipment_writer.writerow(['8', 'Medium Non-stick Frying Pan'])
    equipment_writer.writerow(['9', 'Baking Tray'])
    equipment_writer.writerow(['10', 'Chargrill'])
    equipment_writer.writerow(['11', 'Medium Saucepan'])
    equipment_writer.writerow(['12', 'Food Processor'])
    equipment_writer.writerow(['13', 'Large Ovenproof Frying Pan'])
    equipment_writer.writerow(['14', 'Microwave-safe Bowl'])
    equipment_writer.writerow(['15', 'Whisk'])
    equipment_writer.writerow(['16', 'Glass Dish'])

    #equipment_writer.writerow(['20', ''])
    #equipment_writer.writerow(['21', ''])
    #equipment_writer.writerow(['22', ''])
    #equipment_writer.writerow(['23', ''])
    #equipment_writer.writerow(['24', ''])
    #equipment_writer.writerow(['25', ''])
    #equipment_writer.writerow(['26', ''])
    #equipment_writer.writerow(['27', ''])
    #equipment_writer.writerow(['28', ''])
    #equipment_writer.writerow(['29', ''])
    #
    #equipment_writer.writerow(['30', ''])
    #equipment_writer.writerow(['31', ''])
    #equipment_writer.writerow(['32', ''])
    #equipment_writer.writerow(['33', ''])
    #equipment_writer.writerow(['34', ''])
    #equipment_writer.writerow(['35', ''])
    #equipment_writer.writerow(['36', ''])
    #equipment_writer.writerow(['37', ''])
    #equipment_writer.writerow(['38', ''])
    #equipment_writer.writerow(['39', ''])


    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])

    #
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
    #equipment_writer.writerow(['10', ''])
    #equipment_writer.writerow(['11', ''])
    #equipment_writer.writerow(['12', ''])
    #equipment_writer.writerow(['13', ''])
    #equipment_writer.writerow(['14', ''])
    #equipment_writer.writerow(['15', ''])
    #equipment_writer.writerow(['16', ''])
    #equipment_writer.writerow(['17', ''])
    #equipment_writer.writerow(['18', ''])
    #equipment_writer.writerow(['19', ''])
